#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import os
from chipcompiler.data import WorkspaceStep, Workspace


def _tcl_quote(value: str) -> str:
    """Escape and quote TCL string values if needed."""
    if not isinstance(value, str):
        value = str(value)
    if ' ' in value:
        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'
    return value


def generate_global_var_tcl(workspace: Workspace,
                           step: WorkspaceStep) -> str:
    """Generate global_var.tcl content dynamically from workspace configuration."""
    if not workspace.design.top_module:
        raise ValueError("TOP_NAME (workspace.design.top_module) not set")

    freq_mhz = workspace.parameters.data.get("Frequency max [MHz]")
    if freq_mhz is None:
        raise ValueError("CLK_FREQ_MHZ (Frequency max [MHz]) not set")
    if not isinstance(freq_mhz, (int, float)) or freq_mhz <= 0:
        raise ValueError(f"CLK_FREQ_MHZ must be positive number, got {freq_mhz}")

    rtl_file = step.input.get("verilog", "")
    filelist = workspace.design.input_filelist if workspace.design.input_filelist else workspace.parameters.data.get("File list", "")

    # Prefer filelist if available, otherwise use rtl_file --- IGNORE ---
    has_valid_filelist = filelist and os.path.exists(filelist)
    has_valid_rtl = rtl_file and os.path.exists(rtl_file)

    if not has_valid_filelist and not has_valid_rtl:
        raise ValueError(f"Neither RTL_FILE ({rtl_file}) nor filelist ({filelist}) exists")

    top_design = workspace.design.top_module
    clk_freq_mhz = int(freq_mhz) if isinstance(freq_mhz, float) and freq_mhz.is_integer() else freq_mhz

    netlist_file = step.output.get("verilog", "")
    timing_cell_stat_rpt = step.report.get("stat", "")
    timing_cell_count_rpt = step.report.get("check", "")
    generic_stat_json = step.report.get("stat", "")
    synth_stat_json = step.report.get("stat", "")
    synth_check_rpt = step.report.get("check", "")

    keep_hierarchy = "false"

    pdk = workspace.pdk
    dont_use_cells = pdk.dont_use if pdk.dont_use else []
    dont_use_cells_str = " ".join(dont_use_cells) if dont_use_cells else ""

    tie_low_cell = pdk.tie_low_cell if pdk.tie_low_cell else ""
    tie_low_port = pdk.tie_low_port if pdk.tie_low_port else ""
    tie_high_cell = pdk.tie_high_cell if pdk.tie_high_cell else ""
    tie_high_port = pdk.tie_high_port if pdk.tie_high_port else ""

    lib_files = workspace.pdk.libs if workspace.pdk.libs else []
    lib_stdcell = lib_files[0] if lib_files else ""
    lib_all = " ".join(lib_files) if lib_files else ""

    data_dir = step.data.get("dir", "")

    filelist = workspace.design.input_filelist if workspace.design.input_filelist else workspace.parameters.data.get("File list", "")

    if filelist:
        rtl_source_section = (
            "# RTL source files (from filelist)\n"
            f"set filelist            {_tcl_quote(filelist)}"
        )
    else:
        rtl_source_section = (
            "# RTL source files\n"
            f"set rtl_file            [split {_tcl_quote(rtl_file)}]"
        )

    tcl_content = f"""# Auto-generated by builder.py - DO NOT EDIT MANUALLY
# Generated configuration for Yosys synthesis
# Timestamp: {os.popen('date').read().strip()}

set top_design              {_tcl_quote(top_design)}
set clk_freq_mhz            {clk_freq_mhz}

{rtl_source_section}

# Output files
set final_netlist_file      {_tcl_quote(netlist_file)}
set timing_cell_stat_rpt    {_tcl_quote(timing_cell_stat_rpt)}
set timing_cell_count_rpt   {_tcl_quote(timing_cell_count_rpt)}
set generic_stat_json       {_tcl_quote(generic_stat_json)}
set synth_stat_json         {_tcl_quote(synth_stat_json)}
set synth_check_rpt         {_tcl_quote(synth_check_rpt)}

# Synthesis options
set keep_hierarchy          {keep_hierarchy}

# Cell configurations
set dont_use_cells          {_tcl_quote(dont_use_cells_str) if dont_use_cells_str else '""'}
set tie_low_cell            {_tcl_quote(tie_low_cell) if tie_low_cell else '""'}
set tie_low_port            {_tcl_quote(tie_low_port) if tie_low_port else '""'}
set tie_high_cell           {_tcl_quote(tie_high_cell) if tie_high_cell else '""'}
set tie_high_port           {_tcl_quote(tie_high_port) if tie_high_port else '""'}

# Library files
set lib_stdcell_list        [split {_tcl_quote(lib_stdcell) if lib_stdcell else '""'}]
set lib_list                [split {_tcl_quote(lib_all) if lib_all else '""'}]

# Working directories
set tmp_dir                 {_tcl_quote(os.path.join(data_dir, 'tmp'))}

###############

# Calculate clock period in picoseconds
set clk_period_ps  [expr 1000000.0 / ${{clk_freq_mhz}}]

# Create directories
file mkdir $tmp_dir
set stat_dir [file dirname $synth_stat_json]
if {{![file isdirectory $stat_dir]}} {{
    file mkdir $stat_dir
}}"""

    return tcl_content


def build_step(workspace: Workspace,
               step_name: str,
               input_def: str,
               input_verilog: str,
               output_def: str = None,
               output_verilog: str = None,
               output_gds: str = None) -> WorkspaceStep:
    """
    Build the synthesis step in the specified workspace.

    Note: input_def is not used for synthesis, only input_verilog (RTL).
    Synthesis doesn't produce DEF; output_def points to verilog for flow compatibility.
    """
    step = WorkspaceStep()
    step.name = step_name
    step.tool = "yosys"
    step.version = "0.1"

    step.directory = f"{workspace.directory}/{step.name}_{step.tool}"

    step.config = {
        "dir": f"{step.directory}/config",
    }

    step.input = {
        "verilog": input_verilog,
    }

    if output_verilog is None:
        output_verilog = f"{step.directory}/output/{workspace.design.name}_{step.name}.v"
    if output_def is None:
        output_def = f"{step.directory}/output/{workspace.design.name}_{step.name}.def.gz"
    step.output = {
        "dir": f"{step.directory}/output",
        "def": output_def,
        "verilog": output_verilog,
        "json": f"{step.directory}/output/{workspace.design.name}_{step.name}.json",
        "report": f"{step.directory}/output/{workspace.design.name}_{step.name}.rpt",
    }

    step.data = {
        "dir": f"{step.directory}/data",
        "tmp": f"{step.directory}/data/tmp",
    }

    step.report = {
        "dir": f"{step.directory}/report",
        "stat": f"{step.directory}/report/{step.name}_stat.json",
        "check": f"{step.directory}/report/{step.name}_check.rpt",
    }

    step.log = {
        "dir": f"{step.directory}/log",
        "file": f"{step.directory}/log/{step.name}.log",
    }

    step.script = {
        "dir": f"{step.directory}/script",
        "main": f"{step.directory}/script/{step.name}_main.tcl",
    }

    step.analysis = {
        "dir": f"{step.directory}/analysis",
        "metrics": f"{step.directory}/analysis/{step.name}_metrics.json"
    }  

    return step


def build_step_space(step: WorkspaceStep) -> None:
    """
    Create the workspace directories for the given step.
    """
    os.makedirs(step.directory, exist_ok=True)
    os.makedirs(step.config.get("dir", f"{step.directory}/config"), exist_ok=True)
    os.makedirs(step.output.get("dir", f"{step.directory}/output"), exist_ok=True)
    os.makedirs(step.data.get("dir", f"{step.directory}/data"), exist_ok=True)
    os.makedirs(step.data.get("tmp", f"{step.directory}/data/tmp"), exist_ok=True)
    os.makedirs(step.report.get("dir", f"{step.directory}/report"), exist_ok=True)
    os.makedirs(step.log.get("dir", f"{step.directory}/log"), exist_ok=True)
    os.makedirs(step.script.get("dir", f"{step.directory}/script"), exist_ok=True)


def build_step_config(workspace: Workspace,
                      step: WorkspaceStep):
    """
    Build the configuration files for the synthesis step.

    Creates the following directory structure:
    - script/ subdirectory with all prepared TCL scripts (yosys_synthesis.tcl, init_tech.tcl, abc-opt.script, aig library)
    - data/ subdirectory with generated files (global_var.tcl, tmp/ folder with generated temporary constr files)
    """
    import shutil

    current_dir = os.path.dirname(os.path.abspath(__file__))
    scripts_dir = os.path.abspath(os.path.join(current_dir, 'scripts'))

    for file in ['yosys_synthesis.tcl', 'init_tech.tcl']:
        src = os.path.join(scripts_dir, file)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(step.script['dir'], file))

    abc_script = os.path.join(scripts_dir, 'abc-opt.script')
    if os.path.exists(abc_script):
        shutil.copy2(abc_script, os.path.join(step.script['dir'], 'abc-opt.script'))

    configs_dir = os.path.abspath(os.path.join(current_dir, 'configs'))
    aig_file = os.path.join(configs_dir, 'lazy_man_synth_library.aig')
    if os.path.exists(aig_file):
        shutil.copy2(aig_file, os.path.join(step.script['dir'], 'lazy_man_synth_library.aig'))

    try:
        tcl_content = generate_global_var_tcl(workspace, step)
        global_var_path = os.path.join(step.data['dir'], 'global_var.tcl')
        with open(global_var_path, 'w') as f:
            f.write(tcl_content)
    except (ValueError, IOError) as e:
        print(f"Error generating global_var.tcl: {e}")
        raise
    
def build_environment(workspace: Workspace,
                      step: WorkspaceStep):
    """
    Build the environment for the given step.
    """
    pass

