#!/usr/bin/env python
import os
import subprocess

from chipcompiler.data import StateEnum, Workspace, YosysStep
from chipcompiler.tools.yosys.checklist import YosysChecklist
from chipcompiler.tools.yosys.metrics import build_step_metrics
from chipcompiler.tools.yosys.subflow import YosysSubFlow
from chipcompiler.tools.yosys.utility import check_slang_plugin, get_yosys_runtime


def _run_ecc_synthesis_sta(workspace: Workspace, step: YosysStep, ecc_module=None) -> bool:
    """Run optional ECC STA without making ECC a Yosys import dependency."""
    try:
        from chipcompiler.tools.ecc.runner import run_sta_without_spef

        return run_sta_without_spef(
            workspace=workspace,
            step=step,
            ecc_module=ecc_module,
        )
    except Exception as exc:
        workspace.logger.warning(
            "Post-synthesis STA is unavailable; synthesis result is kept: %s", exc
        )
        return False


def run_step(workspace: Workspace, step: YosysStep, ecc_module=None) -> bool:
    """
    Run the synthesis step using yosys.

    All configuration is provided via global_var.tcl (generated by builder.py).
    No environment variables are required.

    Args:
        workspace: The workspace containing design info
        step: The step workspace with paths and config
        ecc_module: Optional ECC instance used for the post-synthesis STA report

    Returns:
        True if synthesis succeeded, False otherwise
    """
    sub_flow = YosysSubFlow(workspace=workspace, workspace_step=step)
    log_path = step.log.file or ""

    yosys_cmd, yosys_env = get_yosys_runtime()
    if not yosys_cmd:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
        error_msg = "Error: yosys is not available (bundled runtime or PATH)."
        try:
            with open(log_path, "w") as log_file:
                log_file.write(error_msg + "\n")
        except Exception:
            pass
        print(error_msg)
        return False

    input_verilog = step.input.verilog or ""
    input_filelist = workspace.design.input_filelist if workspace.design.input_filelist else ""

    # Validate that at least one of input_verilog or filelist is valid
    has_valid_verilog = input_verilog and os.path.exists(input_verilog)
    has_valid_filelist = input_filelist and os.path.exists(input_filelist)

    if not has_valid_verilog and not has_valid_filelist:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
        print(f"Error: Neither RTL file ({input_verilog}) nor filelist ({input_filelist}) found")
        return False

    try:
        cwd_dir = str(step.script.dir or step.directory)

        cmd = yosys_cmd + ["yosys_synthesis.tcl"]

        with open(log_path, "w") as log_file:
            step_data = getattr(step, "data", None)
            if getattr(step_data, "requires_slang", True) and not check_slang_plugin(
                yosys_cmd=yosys_cmd,
                cwd_dir=cwd_dir,
                yosys_env=yosys_env,
                log_file=log_file,
            ):
                sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
                return False

            result = subprocess.run(
                cmd,
                cwd=cwd_dir,
                env=yosys_env,
                stdout=log_file,
                stderr=subprocess.STDOUT,
            )

        if os.path.exists(step.output.verilog or ""):
            sub_flow.update_step(step_name="run yosys", state=StateEnum.Success)

            _run_ecc_synthesis_sta(
                workspace=workspace,
                step=step,
                ecc_module=ecc_module,
            )

            build_step_metrics(workspace=workspace, step=step)

            sub_flow.update_step(step_name="analysis", state=StateEnum.Success)

            checklist = YosysChecklist(workspace=workspace, workspace_step=step)
            checklist.check()

            return True
        else:
            sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)

            print(
                f"Error: Output netlist not generated at {step.output.verilog}. "
                f"yosys exit code: {result.returncode}"
            )
            return False

    except Exception as e:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Imcomplete)
        print(f"Error running yosys: {e}")
        return False
