#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import subprocess
import os
from chipcompiler.data import WorkspaceStep, Workspace, StateEnum, StepEnum
from chipcompiler.tools.yosys.utility import is_eda_exist, get_yosys_command


def run_step(workspace: Workspace,
             step: WorkspaceStep,
             module=None) -> bool:
    """
    Run the synthesis step using yosys.

    All configuration is provided via global_var.tcl (generated by builder.py).
    No environment variables are required.

    Args:
        workspace: The workspace containing design info
        step: The step workspace with paths and config
        module: Not used for yosys (kept for API compatibility)

    Returns:
        True if synthesis succeeded, False otherwise
    """
    if not is_eda_exist():
        return False

    input_verilog = step.input.get("verilog", "")
    if not input_verilog or not os.path.exists(input_verilog):
        print(f"Error: RTL file not found: {input_verilog}")
        return False

    try:
        cwd_dir = step.script.get("dir", step.directory)

        yosys_cmd = get_yosys_command()
        if not yosys_cmd:
            print("Error: No yosys installation found")
            return False

        cmd = yosys_cmd + ["yosys_synthesis.tcl"]

        with open(step.log["file"], "w") as log_file:
            result = subprocess.run(
                cmd,
                cwd=cwd_dir,
                env=os.environ.copy(),
                stdout=log_file,
                stderr=subprocess.STDOUT,
                timeout=600
            )

        if os.path.exists(step.output["verilog"]):
            return True
        else:
            print(f"Error: Output netlist not generated at {step.output['verilog']}")
            return False

    except subprocess.TimeoutExpired:
        print("Error: Yosys synthesis timed out")
        return False
    except Exception as e:
        print(f"Error running yosys: {e}")
        return False
