#!/usr/bin/env python
import os
import time

import subprocess

from chipcompiler.data import StateEnum, Workspace, WorkspaceStep
from chipcompiler.tools.yosys.checklist import YosysChecklist
from chipcompiler.tools.yosys.metrics import build_step_metrics
from chipcompiler.tools.yosys.subflow import YosysSubFlow
from chipcompiler.tools.yosys.utility import check_slang_plugin, get_yosys_runtime


def run_step(workspace: Workspace,
             step: WorkspaceStep,
             ecc_module=None) -> bool:
    """
    Run the synthesis step using yosys.

    All configuration is provided via global_var.tcl (generated by builder.py).
    No environment variables are required.

    Args:
        workspace: The workspace containing design info
        step: The step workspace with paths and config
        ecc_module: Not used for yosys (kept for API compatibility)

    Returns:
        True if synthesis succeeded, False otherwise
    """
    sub_flow = YosysSubFlow(workspace=workspace, workspace_step=step)

    yosys_cmd, yosys_env = get_yosys_runtime()
    if not yosys_cmd:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
        error_msg = "Error: yosys is not available (bundled runtime or PATH)."
        try:
            with open(step.log["file"], "w") as log_file:
                log_file.write(error_msg + "\n")
        except Exception:
            pass
        print(error_msg)
        return False

    input_verilog = step.input.get("verilog", "")
    input_filelist = workspace.design.input_filelist if workspace.design.input_filelist else ""

    # Validate that at least one of input_verilog or filelist is valid
    has_valid_verilog = input_verilog and os.path.exists(input_verilog)
    has_valid_filelist = input_filelist and os.path.exists(input_filelist)

    if not has_valid_verilog and not has_valid_filelist:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
        print(f"Error: Neither RTL file ({input_verilog}) nor filelist ({input_filelist}) found")
        return False

    try:
        cwd_dir = step.script.get("dir", step.directory)

        cmd = yosys_cmd + ["yosys_synthesis.tcl"]

        with open(step.log["file"], "w") as log_file:
            if not check_slang_plugin(
                yosys_cmd=yosys_cmd,
                cwd_dir=cwd_dir,
                yosys_env=yosys_env,
                log_file=log_file
            ):
                sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
                return False

            result = subprocess.run(
                cmd,
                cwd=cwd_dir,
                env=yosys_env,
                stdout=log_file,
                stderr=subprocess.STDOUT,
                timeout=600
            )

        if os.path.exists(step.output["verilog"]):
            sub_flow.update_step(step_name="run yosys", state=StateEnum.Success)
            
            build_step_metrics(workspace=workspace, step=step)
            
            sub_flow.update_step(step_name="analysis", state=StateEnum.Success)
            
            checklist = YosysChecklist(workspace=workspace, workspace_step=step)
            checklist.check()
            
            return True
        else:
            sub_flow.update_step(step_name="run yosys", state=StateEnum.Invalid)
            
            print(
                f"Error: Output netlist not generated at {step.output['verilog']}. "
                f"yosys exit code: {result.returncode}"
            )
            return False

    except subprocess.TimeoutExpired:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Imcomplete)
        print("Error: Yosys synthesis timed out")
        return False
    except Exception as e:
        sub_flow.update_step(step_name="run yosys", state=StateEnum.Imcomplete)
        print(f"Error running yosys: {e}")
        return False
