# Auto-generated by builder.py - DO NOT EDIT MANUALLY
# Generated configuration for Yosys synthesis
# Timestamp: Thu Jan  8 05:46:42 PM CST 2026

set top_design              gcd
set clk_freq_mhz            100

# RTL source files
set rtl_file            [split /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/origin/gcd.v]

# Output files
set final_netlist_file      /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/output/gcd_Synthesis.v
set timing_cell_stat_rpt    /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/report/Synthesis_stat.json
set timing_cell_count_rpt   /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/report/Synthesis_check.rpt
set generic_stat_json       /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/report/Synthesis_stat.json
set synth_stat_json         /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/report/Synthesis_stat.json
set synth_check_rpt         /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/report/Synthesis_check.rpt

# Synthesis options
set keep_hierarchy          false

# Cell configurations
set dont_use_cells          "DFFSRQX* DFFSRX* *AO222* *2BB2* *AOI222* *AOI33* *OA222* *OAI222* *OAI33* *NOR4* ICG*"
set tie_low_cell            TIELOH7R
set tie_low_port            Z
set tie_high_cell           TIEHIH7R
set tie_high_port           Z

# Library files
set lib_stdcell_list        [split /nfs/home/huangzengrong/ecos/chipcompiler/chipcompiler/thirdparty/icsprout55-pdk/IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CR/liberty/ics55_LLSC_H7CR_ss_rcworst_1p08_125_nldm.lib]
set lib_list                [split "/nfs/home/huangzengrong/ecos/chipcompiler/chipcompiler/thirdparty/icsprout55-pdk/IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CR/liberty/ics55_LLSC_H7CR_ss_rcworst_1p08_125_nldm.lib /nfs/home/huangzengrong/ecos/chipcompiler/chipcompiler/thirdparty/icsprout55-pdk/IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CL/liberty/ics55_LLSC_H7CL_ss_rcworst_1p08_125_nldm.lib"]

# Working directories
set tmp_dir                 /nfs/home/huangzengrong/benchmark/ics55_batch_front/ics55_00001/Synthesis_yosys/data/tmp

###############

# Calculate clock period in picoseconds
set clk_period_ps  [expr 1000000.0 / ${clk_freq_mhz}]

# Create directories
file mkdir $tmp_dir
set stat_dir [file dirname $synth_stat_json]
if {![file isdirectory $stat_dir]} {
    file mkdir $stat_dir
}