name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Convert SSH to HTTPS in gitmodules
        run: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

      - name: Configure git credentials
        run: |
          git config --global url."https://${{ env.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Install LinuxDeploy # For AppImage packaging
        id: install-linuxdeploy
        uses: miurahr/install-linuxdeploy-action@v1.8.0
        with:
          plugins: appimage

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential unzip pkg-config \
            libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev

          sudo apt-get install -y g++-10 cmake ninja-build \
            tcl-dev libgflags-dev libgoogle-glog-dev libboost-all-dev libgtest-dev \
            flex libeigen3-dev libunwind-dev libmetis-dev libgmp-dev bison rustc \
            cargo libhwloc-dev libcairo2-dev libcurl4-openssl-dev libtbb-dev git

      - name: Build release (packaging test)
        env:
          ENABLE_OSS_CAD_SUITE: "true"
          CARGO_PROFILE_RELEASE_STRIP: "false"
        run: CMAKE_EXTRA_OPTIONS='-DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache' ./scripts/build_release.sh
